ALTER TABLE Paciente
DROP COLUMN sexo;
ALTER TABLE Paciente
    ADD COLUMN sexo ENUM('MASCULINO', 'FEMININO', 'OUTROS') NOT NULL;

ALTER TABLE Area
DROP COLUMN nivelRisco;
ALTER TABLE Area
DROP COLUMN prioridade;
ALTER TABLE Area
    ADD COLUMN nivelRisco ENUM('BAIXO', 'MEDIO', 'ALTO', 'MUITO ALTO') NOT NULL;
ALTER TABLE Area
    ADD COLUMN prioridade ENUM('BAIXO', 'MEDIO', 'ALTO', 'MUITO ALTO') NOT NULL;
