START TRANSACTION;

ALTER TABLE agente ADD COLUMN nome VARCHAR(100) NULL;

ALTER TABLE agente MODIFY COLUMN nome VARCHAR(100) NOT NULL;

ALTER TABLE agente DROP FOREIGN KEY agente_ibfk_1;

ALTER TABLE agente DROP COLUMN usuario_id;

DROP TABLE IF EXISTS usuario;

COMMIT;